package com.advantech.model.db1;
// Generated 2017/11/13 下午 01:41:36 by Hibernate Tools 4.3.1

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ErrorCode generated by hbm2java
 */
@Entity
@Table(name = "ErrorCode")
@JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class, property = "id")
public class ErrorCode implements java.io.Serializable {

    private int id;
    private String name;

    @JsonIgnore
    private Set<ActionCode> actionCodes = new HashSet<ActionCode>(0);

    @JsonIgnore
    private Set<Countermeasure> countermeasures = new HashSet<Countermeasure>(0);

    public ErrorCode() {
    }

    public ErrorCode(String name) {
        this.name = name;
    }

    public ErrorCode(Set<ActionCode> actionCodes, Set<Countermeasure> countermeasures, String name) {
        this.actionCodes = actionCodes;
        this.countermeasures = countermeasures;
        this.name = name;
    }

    @Id
    @GeneratedValue
    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "errorCode")
    public Set<ActionCode> getActionCodes() {
        return this.actionCodes;
    }

    public void setActionCodes(Set<ActionCode> actionCodes) {
        this.actionCodes = actionCodes;
    }

    @ManyToMany(fetch = FetchType.LAZY)
    @JoinTable(name = "Countermeasure_ErrorCode_REF", joinColumns = {
        @JoinColumn(name = "ec_id", nullable = false, updatable = false)}, inverseJoinColumns = {
        @JoinColumn(name = "cm_id", nullable = false, updatable = false)})
    public Set<Countermeasure> getCountermeasures() {
        return this.countermeasures;
    }

    public void setCountermeasures(Set<Countermeasure> countermeasures) {
        this.countermeasures = countermeasures;
    }

    @Column(name = "name", nullable = false)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

}
