package com.advantech.model;
// Generated 2017/11/13 下午 01:41:36 by Hibernate Tools 4.3.1

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.voodoodyne.jackson.jsog.JSOGGenerator;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ActionCode generated by hbm2java
 */
@Entity
@Table(name = "ActionCode")
@JsonIdentityInfo(generator = JSOGGenerator.class, property = "id")
public class ActionCode implements java.io.Serializable {

    private int id;
    private String name;
    private ErrorCode errorCode;
    
    @JsonIgnore
    private Set<ActionCodeMapping> actionCodeMappings = new HashSet<ActionCodeMapping>(0);
    
    @JsonIgnore
    private Set<Countermeasure> countermeasures = new HashSet<Countermeasure>(0);

    public ActionCode() {
    }

    public ActionCode(String name) {
        this.name = name;
    }

    public ActionCode(Set<ActionCodeMapping> actionCodeMappings, Set<Countermeasure> countermeasures, ErrorCode errorCode, String name) {
        this.actionCodeMappings = actionCodeMappings;
        this.countermeasures = countermeasures;
        this.errorCode = errorCode;
        this.name = name;
    }

    @Id
    @GeneratedValue
    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "actionCode")
    public Set<ActionCodeMapping> getActionCodeMappings() {
        return this.actionCodeMappings;
    }

    public void setActionCodeMappings(Set<ActionCodeMapping> actionCodeMappings) {
        this.actionCodeMappings = actionCodeMappings;
    }

    @ManyToMany(fetch = FetchType.LAZY)
    @JoinTable(name = "Countermeasure_ActionCode_REF", joinColumns = {
        @JoinColumn(name = "ac_id", nullable = false, updatable = false)}, inverseJoinColumns = {
        @JoinColumn(name = "cm_id", nullable = false, updatable = false)})
    public Set<Countermeasure> getCountermeasures() {
        return this.countermeasures;
    }

    public void setCountermeasures(Set<Countermeasure> countermeasures) {
        this.countermeasures = countermeasures;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ec_id")
    public ErrorCode getErrorCode() {
        return this.errorCode;
    }

    public void setErrorCode(ErrorCode errorCode) {
        this.errorCode = errorCode;
    }

    @Column(name = "name", nullable = false)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

}
