package com.advantech.model;
// Generated 2017/11/13 下午 01:41:36 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ActionCodeMapping generated by hbm2java
 */
@Entity
@Table(name = "ActionCodeMapping")
public class ActionCodeMapping implements java.io.Serializable {

    private int id;
    private ActionCode actionCode;
    private String manager;
    private String sitefloor;
    private String userName;

    public ActionCodeMapping() {
    }

    public ActionCodeMapping(String manager) {
        this.manager = manager;
    }

    public ActionCodeMapping(ActionCode actionCode, String manager, String sitefloor, String userName) {
        this.actionCode = actionCode;
        this.manager = manager;
        this.sitefloor = sitefloor;
        this.userName = userName;
    }

    @Id
    @GeneratedValue

    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ac_id")
    public ActionCode getActionCode() {
        return this.actionCode;
    }

    public void setActionCode(ActionCode actionCode) {
        this.actionCode = actionCode;
    }

    @Column(name = "manager", nullable = false, length = 10)
    public String getManager() {
        return this.manager;
    }

    public void setManager(String manager) {
        this.manager = manager;
    }

    @Column(name = "sitefloor", length = 10)
    public String getSitefloor() {
        return this.sitefloor;
    }

    public void setSitefloor(String sitefloor) {
        this.sitefloor = sitefloor;
    }

    @Column(name = "user_name", length = 20)
    public String getUserName() {
        return this.userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

}
