package com.advantech.model;
// Generated 2017/3/27 上午 08:57:09 by Hibernate Tools 4.3.1

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Floor generated by hbm2java
 */
@Entity
@Table(name = "Floor",
         schema = "dbo",
         catalog = "E_Document"
)
@JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class, property = "id")
public class Floor implements java.io.Serializable {

    private int id;
    private String name;

    @JsonIgnore
    private Set<Identit> identits = new HashSet<Identit>(0);

    @JsonIgnore
    private Set<SheetSpe> sheetSpes = new HashSet<SheetSpe>(0);

    public Floor() {
    }

    public Floor(int id, String name) {
        this.id = id;
        this.name = name;
    }

    public Floor(int id, String name, Set<Identit> identits, Set<SheetSpe> sheetSpes) {
        this.id = id;
        this.name = name;
        this.identits = identits;
        this.sheetSpes = sheetSpes;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @Column(name = "name", nullable = false, length = 50)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "floor")
    public Set<Identit> getIdentits() {
        return this.identits;
    }

    public void setIdentits(Set<Identit> identits) {
        this.identits = identits;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "floor")
    public Set<SheetSpe> getSheetSpes() {
        return this.sheetSpes;
    }

    public void setSheetSpes(Set<SheetSpe> sheetSpes) {
        this.sheetSpes = sheetSpes;
    }

}
