package com.advantech.model;
// Generated 2017/4/7 下午 02:26:06 by Hibernate Tools 4.3.1

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;
import java.util.HashSet;
import java.util.Objects;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import org.apache.commons.lang3.ObjectUtils;

/**
 * Flow generated by hbm2java
 */
@Entity
@Table(name = "Flow",
        uniqueConstraints = @UniqueConstraint(columnNames = "name")
)
@JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class, property = "id", scope = Flow.class)
public class Flow implements java.io.Serializable, Comparable<Flow> {

    private int id;
    private FlowGroup flowGroup;
    private String name;

    @JsonIgnore
    private Set<Worktime> worktimesForTestFlowId = new HashSet<Worktime>(0);

    @JsonIgnore
    private Set<Worktime> worktimesForPackingFlowId = new HashSet<Worktime>(0);

    @JsonIgnore
    private Set<Flow> flowsForTestFlowId = new HashSet<Flow>(0);

    @JsonIgnore
    private Set<Flow> flowsForBabFlowId = new HashSet<Flow>(0);

    @JsonIgnore
    private Set<Worktime> worktimesForBabFlowId = new HashSet<Worktime>(0);

    public Flow() {
    }

    public Flow(int id) {
        this.id = id;
    }

    public Flow(int id, FlowGroup flowGroup, String name, Set<Worktime> worktimesForTestFlowId, Set<Worktime> worktimesForPackingFlowId, Set<Flow> flowsForTestFlowId, Set<Flow> flowsForBabFlowId, Set<Worktime> worktimesForBabFlowId) {
        this.id = id;
        this.flowGroup = flowGroup;
        this.name = name;
        this.worktimesForTestFlowId = worktimesForTestFlowId;
        this.worktimesForPackingFlowId = worktimesForPackingFlowId;
        this.flowsForTestFlowId = flowsForTestFlowId;
        this.flowsForBabFlowId = flowsForBabFlowId;
        this.worktimesForBabFlowId = worktimesForBabFlowId;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "flow_group_id")
    public FlowGroup getFlowGroup() {
        return this.flowGroup;
    }

    public void setFlowGroup(FlowGroup flowGroup) {
        this.flowGroup = flowGroup;
    }

    @Column(name = "name", length = 100)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "flowByTestFlowId")
    public Set<Worktime> getWorktimesForTestFlowId() {
        return this.worktimesForTestFlowId;
    }

    public void setWorktimesForTestFlowId(Set<Worktime> worktimesForTestFlowId) {
        this.worktimesForTestFlowId = worktimesForTestFlowId;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "flowByPackingFlowId")
    public Set<Worktime> getWorktimesForPackingFlowId() {
        return this.worktimesForPackingFlowId;
    }

    public void setWorktimesForPackingFlowId(Set<Worktime> worktimesForPackingFlowId) {
        this.worktimesForPackingFlowId = worktimesForPackingFlowId;
    }

    @ManyToMany(fetch = FetchType.LAZY)
    @JoinTable(name = "Flow_REF", schema = "dbo", catalog = "E_Document", joinColumns = {
        @JoinColumn(name = "bab_flow_id", nullable = false, updatable = false)}, inverseJoinColumns = {
        @JoinColumn(name = "test_flow_id", nullable = false, updatable = false)})
    public Set<Flow> getFlowsForTestFlowId() {
        return this.flowsForTestFlowId;
    }

    public void setFlowsForTestFlowId(Set<Flow> flowsForTestFlowId) {
        this.flowsForTestFlowId = flowsForTestFlowId;
    }

    @ManyToMany(fetch = FetchType.LAZY)
    @JoinTable(name = "Flow_REF", schema = "dbo", catalog = "E_Document", joinColumns = {
        @JoinColumn(name = "test_flow_id", nullable = false, updatable = false)}, inverseJoinColumns = {
        @JoinColumn(name = "bab_flow_id", nullable = false, updatable = false)})
    public Set<Flow> getFlowsForBabFlowId() {
        return this.flowsForBabFlowId;
    }

    public void setFlowsForBabFlowId(Set<Flow> flowsForBabFlowId) {
        this.flowsForBabFlowId = flowsForBabFlowId;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "flowByBabFlowId")
    public Set<Worktime> getWorktimesForBabFlowId() {
        return this.worktimesForBabFlowId;
    }

    public void setWorktimesForBabFlowId(Set<Worktime> worktimesForBabFlowId) {
        this.worktimesForBabFlowId = worktimesForBabFlowId;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 97 * hash + Objects.hashCode(this.name);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Flow other = (Flow) obj;
        if (Objects.equals(this.id, other.id)) {
            return true;
        }
        if (!Objects.equals(this.name, other.name)) {
            return false;
        }
        return true;
    }

    @Override
    public int compareTo(Flow o) {
        return ObjectUtils.compare(this.id, o.getId()); 
    }

}
