package com.advantech.model;
// Generated 2017/3/30 下午 01:07:49 by Hibernate Tools 4.3.1

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Identit generated by hbm2java
 */
@Entity
@Table(name = "Identit",
         schema = "dbo",
         catalog = "E_Document"
)
@JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class, property = "id")
public class Identit implements java.io.Serializable {

    private int id;
    private Floor floor;
    private UserType userType;
    private String jobnumber;
    private String password;
    private String name;
    private Integer permission;
    private String email;

    @JsonIgnore
    private Set<SheetSpe> sheetSpesForEeOwnerId = new HashSet<SheetSpe>(0);

    @JsonIgnore
    private Set<SheetSpe> sheetSpesForSpeOwnerId = new HashSet<SheetSpe>(0);

    @JsonIgnore
    private Set<SheetSpe> sheetSpesForQcOwnerId = new HashSet<SheetSpe>(0);

    public Identit() {
    }

    public Identit(int id) {
        this.id = id;
    }

    public Identit(int id, Floor floor, UserType userType, String jobnumber, String password, String name, Integer permission, String email, Set<SheetSpe> sheetSpesForEeOwnerId, Set<SheetSpe> sheetSpesForSpeOwnerId, Set<SheetSpe> sheetSpesForQcOwnerId) {
        this.id = id;
        this.floor = floor;
        this.userType = userType;
        this.jobnumber = jobnumber;
        this.password = password;
        this.name = name;
        this.permission = permission;
        this.email = email;
        this.sheetSpesForEeOwnerId = sheetSpesForEeOwnerId;
        this.sheetSpesForSpeOwnerId = sheetSpesForSpeOwnerId;
        this.sheetSpesForQcOwnerId = sheetSpesForQcOwnerId;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "floor_id")
    public Floor getFloor() {
        return this.floor;
    }

    public void setFloor(Floor floor) {
        this.floor = floor;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "usertype_id")
    public UserType getUserType() {
        return this.userType;
    }

    public void setUserType(UserType userType) {
        this.userType = userType;
    }

    @Column(name = "jobnumber", length = 50)
    public String getJobnumber() {
        return this.jobnumber;
    }

    public void setJobnumber(String jobnumber) {
        this.jobnumber = jobnumber;
    }

    @Column(name = "password", length = 50)
    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    @Column(name = "name", length = 50)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "permission")
    public Integer getPermission() {
        return this.permission;
    }

    public void setPermission(Integer permission) {
        this.permission = permission;
    }

    @Column(name = "email", length = 100)
    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "identitByEeOwnerId")
    public Set<SheetSpe> getSheetSpesForEeOwnerId() {
        return this.sheetSpesForEeOwnerId;
    }

    public void setSheetSpesForEeOwnerId(Set<SheetSpe> sheetSpesForEeOwnerId) {
        this.sheetSpesForEeOwnerId = sheetSpesForEeOwnerId;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "identitBySpeOwnerId")
    public Set<SheetSpe> getSheetSpesForSpeOwnerId() {
        return this.sheetSpesForSpeOwnerId;
    }

    public void setSheetSpesForSpeOwnerId(Set<SheetSpe> sheetSpesForSpeOwnerId) {
        this.sheetSpesForSpeOwnerId = sheetSpesForSpeOwnerId;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "identitByQcOwnerId")
    public Set<SheetSpe> getSheetSpesForQcOwnerId() {
        return this.sheetSpesForQcOwnerId;
    }

    public void setSheetSpesForQcOwnerId(Set<SheetSpe> sheetSpesForQcOwnerId) {
        this.sheetSpesForQcOwnerId = sheetSpesForQcOwnerId;
    }

}
