package com.advantech.model;
// Generated 2017/5/25 上午 10:45:32 by Hibernate Tools 4.3.1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

/**
 * BabTagNameComparison generated by hbm2java
 */
@Entity
@Table(name = "Line_User_REF2")
public class LineUserReference implements java.io.Serializable {

    private LineUserReferenceId id;
    private int station;

    public LineUserReference() {
    }

    public LineUserReference(LineUserReferenceId id) {
        this.id = id;
    }

    @EmbeddedId
    @AttributeOverrides({
        @AttributeOverride(name = "line_id", column = @Column(name = "line_id", nullable = false))
        , 
        @AttributeOverride(name = "user_id", column = @Column(name = "user_id", nullable = false))
    })
    public LineUserReferenceId getId() {
        return this.id;
    }

    public void setId(LineUserReferenceId id) {
        this.id = id;
    }

    @NotNull
    @Column(name = "station")
    public int getStation() {
        return this.station;
    }

    public void setStation(int station) {
        this.station = station;
    }

}
