package com.advantech.model;
// Generated 2017/3/15 上午 09:14:05 by Hibernate Tools 4.3.1

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;
import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Pending generated by hbm2java
 */
@Entity
@Table(name = "Pending",
        schema = "dbo",
        catalog = "E_Document"
)
@JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class, property = "id")
public class Pending implements java.io.Serializable {

    private int id;
    private SheetSpe sheetSpe;
    private String typeName;
    private BigDecimal time;

    public Pending() {
    }

    public Pending(int id) {
        this.id = id;
    }

    public Pending(int id, SheetSpe sheetSpe, String typeName, BigDecimal time) {
        this.id = id;
        this.sheetSpe = sheetSpe;
        this.typeName = typeName;
        this.time = time;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "sheet_spe_id")
    public SheetSpe getSheetSpe() {
        return this.sheetSpe;
    }

    public void setSheetSpe(SheetSpe sheetSpe) {
        this.sheetSpe = sheetSpe;
    }

    @Column(name = "type_name", length = 50)
    public String getTypeName() {
        return this.typeName;
    }

    public void setTypeName(String typeName) {
        this.typeName = typeName;
    }

    @Column(name = "time", precision = 10, scale = 1)
    public BigDecimal getTime() {
        return this.time;
    }

    public void setTime(BigDecimal time) {
        this.time = time;
    }

}
