package com.advantech.model;
// Generated 2017/3/30 上午 11:57:12 by Hibernate Tools 4.3.1

import com.fasterxml.jackson.annotation.JsonFormat;
import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SheetView generated by hbm2java
 */
@Entity
@Table(name = "Sheet_Main_view",
        schema = "dbo",
        catalog = "E_Document"
)
public class SheetView implements java.io.Serializable {

    private int rowId;
    private String modelName;
    private String typeName;
    private BigDecimal productionWt;
    private BigDecimal totalModule;
    private Integer setupTime;
    private BigDecimal cleanPanel;
    private BigDecimal assy;
    private BigDecimal t1;
    private BigDecimal t2;
    private BigDecimal t3;
    private BigDecimal t4;
    private BigDecimal packing;
    private BigDecimal downBiRi;
    private BigDecimal upBiRi;
    private BigDecimal biCost;
    private Integer vibration;
    private Integer hiPotLeakage;
    private BigDecimal coldBoot;
    private BigDecimal warmBoot;
    private BigDecimal assyToT1;
    private BigDecimal t2ToPacking;
    private String floorName;
    private String pendingName;
    private BigDecimal pendingTime;
    private String burnIn;
    private BigDecimal biTime;
    private BigDecimal biTemperature;
    private String speOwnerName;
    private String eeOwnerName;
    private String qcOwnerName;
    private String assyPackingSop;
    private String testSop;
    private Integer keypartA;
    private Integer keypartB;
    private String preAssyName;
    private String babFlowName;
    private String testFlowName;
    private String packingFlowName;
    private Character partLink;
    private Integer ce;
    private Integer ul;
    private Integer rohs;
    private Integer weee;
    private Integer madeInTaiwan;
    private Integer fcc;
    private Integer eac;
    private BigDecimal nInOneCollectionBox;
    private Character partNoAttributeMaintain;
    private Integer assyStation;
    private Integer packingStation;
    private BigDecimal assyLeadTime;
    private BigDecimal assyKanbanTime;
    private BigDecimal packingLeadTime;
    private BigDecimal packingKanbanTime;
    private BigDecimal cleanPanelAndAssembly;
    private Date modifiedDate;

    public SheetView() {
    }

    public SheetView(int rowId, String modelName, String typeName, BigDecimal productionWt, BigDecimal totalModule, Integer setupTime, BigDecimal cleanPanel, BigDecimal assy, BigDecimal t1, BigDecimal t2, BigDecimal t3, BigDecimal t4, BigDecimal packing, BigDecimal downBiRi, BigDecimal upBiRi, BigDecimal biCost, Integer vibration, Integer hiPotLeakage, BigDecimal coldBoot, BigDecimal warmBoot, BigDecimal assyToT1, BigDecimal t2ToPacking, String floorName, String pendingName, BigDecimal pendingTime, String burnIn, BigDecimal biTime, BigDecimal biTemperature, String speOwnerName, String eeOwnerName, String qcOwnerName, String assyPackingSop, String testSop, Integer keypartA, Integer keypartB, String preAssyName, String babFlowName, String testFlowName, String packingFlowName, Character partLink, Integer ce, Integer ul, Integer rohs, Integer weee, Integer madeInTaiwan, Integer fcc, Integer eac, BigDecimal nInOneCollectionBox, Character partNoAttributeMaintain, Integer assyStation, Integer packingStation, BigDecimal assyLeadTime, BigDecimal assyKanbanTime, BigDecimal packingLeadTime, BigDecimal packingKanbanTime, BigDecimal cleanPanelAndAssembly, Date modifiedDate) {
        this.rowId = rowId;
        this.modelName = modelName;
        this.typeName = typeName;
        this.productionWt = productionWt;
        this.totalModule = totalModule;
        this.setupTime = setupTime;
        this.cleanPanel = cleanPanel;
        this.assy = assy;
        this.t1 = t1;
        this.t2 = t2;
        this.t3 = t3;
        this.t4 = t4;
        this.packing = packing;
        this.downBiRi = downBiRi;
        this.upBiRi = upBiRi;
        this.biCost = biCost;
        this.vibration = vibration;
        this.hiPotLeakage = hiPotLeakage;
        this.coldBoot = coldBoot;
        this.warmBoot = warmBoot;
        this.assyToT1 = assyToT1;
        this.t2ToPacking = t2ToPacking;
        this.floorName = floorName;
        this.pendingName = pendingName;
        this.pendingTime = pendingTime;
        this.burnIn = burnIn;
        this.biTime = biTime;
        this.biTemperature = biTemperature;
        this.speOwnerName = speOwnerName;
        this.eeOwnerName = eeOwnerName;
        this.qcOwnerName = qcOwnerName;
        this.assyPackingSop = assyPackingSop;
        this.testSop = testSop;
        this.keypartA = keypartA;
        this.keypartB = keypartB;
        this.preAssyName = preAssyName;
        this.babFlowName = babFlowName;
        this.testFlowName = testFlowName;
        this.packingFlowName = packingFlowName;
        this.partLink = partLink;
        this.ce = ce;
        this.ul = ul;
        this.rohs = rohs;
        this.weee = weee;
        this.madeInTaiwan = madeInTaiwan;
        this.fcc = fcc;
        this.eac = eac;
        this.nInOneCollectionBox = nInOneCollectionBox;
        this.partNoAttributeMaintain = partNoAttributeMaintain;
        this.assyStation = assyStation;
        this.packingStation = packingStation;
        this.assyLeadTime = assyLeadTime;
        this.assyKanbanTime = assyKanbanTime;
        this.packingLeadTime = packingLeadTime;
        this.packingKanbanTime = packingKanbanTime;
        this.cleanPanelAndAssembly = cleanPanelAndAssembly;
        this.modifiedDate = modifiedDate;
    }

    @Id
    @Column(name = "rowId", unique = true, nullable = false)
    public int getRowId() {
        return this.rowId;
    }

    public void setRowId(int rowId) {
        this.rowId = rowId;
    }

    @Column(name = "assy", precision = 10, scale = 1)
    public BigDecimal getAssy() {
        return this.assy;
    }

    public void setAssy(BigDecimal assy) {
        this.assy = assy;
    }

    @Column(name = "assyKanbanTime", precision = 10, scale = 1)
    public BigDecimal getAssyKanbanTime() {
        return this.assyKanbanTime;
    }

    public void setAssyKanbanTime(BigDecimal assyKanbanTime) {
        this.assyKanbanTime = assyKanbanTime;
    }

    @Column(name = "assyLeadTime", precision = 10, scale = 1)
    public BigDecimal getAssyLeadTime() {
        return this.assyLeadTime;
    }

    public void setAssyLeadTime(BigDecimal assyLeadTime) {
        this.assyLeadTime = assyLeadTime;
    }

    @Column(name = "assyPackingSop")
    public String getAssyPackingSop() {
        return this.assyPackingSop;
    }

    public void setAssyPackingSop(String assyPackingSop) {
        this.assyPackingSop = assyPackingSop;
    }

    @Column(name = "assyStation")
    public Integer getAssyStation() {
        return this.assyStation;
    }

    public void setAssyStation(Integer assyStation) {
        this.assyStation = assyStation;
    }

    @Column(name = "assyToT1", precision = 10, scale = 1)
    public BigDecimal getAssyToT1() {
        return this.assyToT1;
    }

    public void setAssyToT1(BigDecimal assyToT1) {
        this.assyToT1 = assyToT1;
    }

    @Column(name = "babFlowName")
    public String getBabFlowName() {
        return this.babFlowName;
    }

    public void setBabFlowName(String babFlowName) {
        this.babFlowName = babFlowName;
    }

    @Column(name = "biCost", precision = 10, scale = 1)
    public BigDecimal getBiCost() {
        return this.biCost;
    }

    public void setBiCost(BigDecimal biCost) {
        this.biCost = biCost;
    }

    @Column(name = "biTemperature", precision = 10, scale = 1)
    public BigDecimal getBiTemperature() {
        return this.biTemperature;
    }

    public void setBiTemperature(BigDecimal biTemperature) {
        this.biTemperature = biTemperature;
    }

    @Column(name = "biTime", precision = 10, scale = 1)
    public BigDecimal getBiTime() {
        return this.biTime;
    }

    public void setBiTime(BigDecimal biTime) {
        this.biTime = biTime;
    }

    @Column(name = "burnIn")
    public String getBurnIn() {
        return this.burnIn;
    }

    public void setBurnIn(String burnIn) {
        this.burnIn = burnIn;
    }

    @Column(name = "ce")
    public Integer getCe() {
        return this.ce;
    }

    public void setCe(Integer ce) {
        this.ce = ce;
    }

    @Column(name = "cleanPanel", precision = 10, scale = 1)
    public BigDecimal getCleanPanel() {
        return this.cleanPanel;
    }

    public void setCleanPanel(BigDecimal cleanPanel) {
        this.cleanPanel = cleanPanel;
    }

    @Column(name = "cleanPanelAndAssembly", precision = 10, scale = 1)
    public BigDecimal getCleanPanelAndAssembly() {
        return this.cleanPanelAndAssembly;
    }

    public void setCleanPanelAndAssembly(BigDecimal cleanPanelAndAssembly) {
        this.cleanPanelAndAssembly = cleanPanelAndAssembly;
    }

    @Column(name = "coldBoot", precision = 10, scale = 1)
    public BigDecimal getColdBoot() {
        return this.coldBoot;
    }

    public void setColdBoot(BigDecimal coldBoot) {
        this.coldBoot = coldBoot;
    }

    @Column(name = "downBiRi", precision = 10, scale = 1)
    public BigDecimal getDownBiRi() {
        return this.downBiRi;
    }

    public void setDownBiRi(BigDecimal downBiRi) {
        this.downBiRi = downBiRi;
    }

    @Column(name = "eac")
    public Integer getEac() {
        return this.eac;
    }

    public void setEac(Integer eac) {
        this.eac = eac;
    }

    @Column(name = "eeOwnerName")
    public String getEeOwnerName() {
        return this.eeOwnerName;
    }

    public void setEeOwnerName(String eeOwnerName) {
        this.eeOwnerName = eeOwnerName;
    }

    @Column(name = "fcc")
    public Integer getFcc() {
        return this.fcc;
    }

    public void setFcc(Integer fcc) {
        this.fcc = fcc;
    }

    @Column(name = "floorName")
    public String getFloorName() {
        return this.floorName;
    }

    public void setFloorName(String floorName) {
        this.floorName = floorName;
    }

    @Column(name = "hiPotLeakage")
    public Integer getHiPotLeakage() {
        return this.hiPotLeakage;
    }

    public void setHiPotLeakage(Integer hiPotLeakage) {
        this.hiPotLeakage = hiPotLeakage;
    }

    @Column(name = "keypartA")
    public Integer getKeypartA() {
        return this.keypartA;
    }

    public void setKeypartA(Integer keypartA) {
        this.keypartA = keypartA;
    }

    @Column(name = "keypartB")
    public Integer getKeypartB() {
        return this.keypartB;
    }

    public void setKeypartB(Integer keypartB) {
        this.keypartB = keypartB;
    }

    @Column(name = "madeInTaiwan")
    public Integer getMadeInTaiwan() {
        return this.madeInTaiwan;
    }

    public void setMadeInTaiwan(Integer madeInTaiwan) {
        this.madeInTaiwan = madeInTaiwan;
    }

    @Column(name = "modelName", nullable = false, length = 50)
    public String getModelName() {
        return this.modelName;
    }

    public void setModelName(String modelName) {
        this.modelName = modelName;
    }

    @JsonFormat(pattern = "yyyy-MM-dd'T'kk:mm:ss.SSS'Z'", timezone = "GMT+8")
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "modifiedDate", updatable = false, length = 23)
    public Date getModifiedDate() {
        return this.modifiedDate;
    }

    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }

    @Column(name = "nInOneCollectionBox", precision = 10, scale = 1)
    public BigDecimal getnInOneCollectionBox() {
        return this.nInOneCollectionBox;
    }

    public void setnInOneCollectionBox(BigDecimal nInOneCollectionBox) {
        this.nInOneCollectionBox = nInOneCollectionBox;
    }

    @Column(name = "packing", precision = 10, scale = 1)
    public BigDecimal getPacking() {
        return this.packing;
    }

    public void setPacking(BigDecimal packing) {
        this.packing = packing;
    }

    @Column(name = "packingFlowName")
    public String getPackingFlowName() {
        return this.packingFlowName;
    }

    public void setPackingFlowName(String packingFlowName) {
        this.packingFlowName = packingFlowName;
    }

    @Column(name = "packingKanbanTime", precision = 10, scale = 1)
    public BigDecimal getPackingKanbanTime() {
        return this.packingKanbanTime;
    }

    public void setPackingKanbanTime(BigDecimal packingKanbanTime) {
        this.packingKanbanTime = packingKanbanTime;
    }

    @Column(name = "packingLeadTime", precision = 10, scale = 1)
    public BigDecimal getPackingLeadTime() {
        return this.packingLeadTime;
    }

    public void setPackingLeadTime(BigDecimal packingLeadTime) {
        this.packingLeadTime = packingLeadTime;
    }

    @Column(name = "packingStation")
    public Integer getPackingStation() {
        return this.packingStation;
    }

    public void setPackingStation(Integer packingStation) {
        this.packingStation = packingStation;
    }

    @Column(name = "partLink")
    public Character getPartLink() {
        return this.partLink;
    }

    public void setPartLink(Character partLink) {
        this.partLink = partLink;
    }

    @Column(name = "partNoAttributeMaintain")
    public Character getPartNoAttributeMaintain() {
        return this.partNoAttributeMaintain;
    }

    public void setPartNoAttributeMaintain(Character partNoAttributeMaintain) {
        this.partNoAttributeMaintain = partNoAttributeMaintain;
    }

    @Column(name = "pendingName")
    public String getPendingName() {
        return this.pendingName;
    }

    public void setPendingName(String pendingName) {
        this.pendingName = pendingName;
    }

    @Column(name = "pendingTime", precision = 10, scale = 1)
    public BigDecimal getPendingTime() {
        return this.pendingTime;
    }

    public void setPendingTime(BigDecimal pendingTime) {
        this.pendingTime = pendingTime;
    }

    @Column(name = "preAssyName")
    public String getPreAssyName() {
        return this.preAssyName;
    }

    public void setPreAssyName(String preAssyName) {
        this.preAssyName = preAssyName;
    }

    @Column(name = "ProductionWt", precision = 10, scale = 1)
    public BigDecimal getProductionWt() {
        return this.productionWt;
    }

    public void setProductionWt(BigDecimal productionWt) {
        this.productionWt = productionWt;
    }

    @Column(name = "qcOwnerName")
    public String getQcOwnerName() {
        return this.qcOwnerName;
    }

    public void setQcOwnerName(String qcOwnerName) {
        this.qcOwnerName = qcOwnerName;
    }

    @Column(name = "rohs")
    public Integer getRohs() {
        return this.rohs;
    }

    public void setRohs(Integer rohs) {
        this.rohs = rohs;
    }

    @Column(name = "setupTime")
    public Integer getSetupTime() {
        return this.setupTime;
    }

    public void setSetupTime(Integer setupTime) {
        this.setupTime = setupTime;
    }

    @Column(name = "speOwnerName")
    public String getSpeOwnerName() {
        return this.speOwnerName;
    }

    public void setSpeOwnerName(String speOwnerName) {
        this.speOwnerName = speOwnerName;
    }

    @Column(name = "t1", precision = 10, scale = 1)
    public BigDecimal getT1() {
        return this.t1;
    }

    public void setT1(BigDecimal t1) {
        this.t1 = t1;
    }

    @Column(name = "t2", precision = 10, scale = 1)
    public BigDecimal getT2() {
        return this.t2;
    }

    public void setT2(BigDecimal t2) {
        this.t2 = t2;
    }

    @Column(name = "t2ToPacking", precision = 10, scale = 1)
    public BigDecimal getT2ToPacking() {
        return this.t2ToPacking;
    }

    public void setT2ToPacking(BigDecimal t2ToPacking) {
        this.t2ToPacking = t2ToPacking;
    }

    @Column(name = "t3", precision = 10, scale = 1)
    public BigDecimal getT3() {
        return this.t3;
    }

    public void setT3(BigDecimal t3) {
        this.t3 = t3;
    }

    @Column(name = "t4", precision = 10, scale = 1)
    public BigDecimal getT4() {
        return this.t4;
    }

    public void setT4(BigDecimal t4) {
        this.t4 = t4;
    }

    @Column(name = "testFlowName")
    public String getTestFlowName() {
        return this.testFlowName;
    }

    public void setTestFlowName(String testFlowName) {
        this.testFlowName = testFlowName;
    }

    @Column(name = "testSop")
    public String getTestSop() {
        return this.testSop;
    }

    public void setTestSop(String testSop) {
        this.testSop = testSop;
    }

    @Column(name = "totalModule", precision = 10, scale = 1)
    public BigDecimal getTotalModule() {
        return this.totalModule;
    }

    public void setTotalModule(BigDecimal totalModule) {
        this.totalModule = totalModule;
    }

    @Column(name = "typeName")
    public String getTypeName() {
        return this.typeName;
    }

    public void setTypeName(String typeName) {
        this.typeName = typeName;
    }

    @Column(name = "ul")
    public Integer getUl() {
        return this.ul;
    }

    public void setUl(Integer ul) {
        this.ul = ul;
    }

    @Column(name = "upBiRi", precision = 10, scale = 1)
    public BigDecimal getUpBiRi() {
        return this.upBiRi;
    }

    public void setUpBiRi(BigDecimal upBiRi) {
        this.upBiRi = upBiRi;
    }

    @Column(name = "vibration")
    public Integer getVibration() {
        return this.vibration;
    }

    public void setVibration(Integer vibration) {
        this.vibration = vibration;
    }

    @Column(name = "warmBoot", precision = 10, scale = 1)
    public BigDecimal getWarmBoot() {
        return this.warmBoot;
    }

    public void setWarmBoot(BigDecimal warmBoot) {
        this.warmBoot = warmBoot;
    }

    @Column(name = "weee")
    public Integer getWeee() {
        return this.weee;
    }

    public void setWeee(Integer weee) {
        this.weee = weee;
    }

}
