package com.advantech.model;
// Generated 2017/3/30 上午 11:57:12 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;

/**
 * SheetView generated by hbm2java
 */
public interface SheetView {

    public int getId();

    public String getModelName();

    public String getTypeName();

    public BigDecimal getProductionWt();

    public BigDecimal getTotalModule();

    public Integer getSetupTime();

    public BigDecimal getCleanPanel();

    public BigDecimal getAssy();

    public BigDecimal getT1();

    public BigDecimal getT2();

    public BigDecimal getT3();

    public BigDecimal getT4();

    public BigDecimal getPacking();

    public BigDecimal getDownBiRi();

    public BigDecimal getUpBiRi();

    public BigDecimal getBiCost();

    public Integer getVibration();

    public Integer getHiPotLeakage();

    public BigDecimal getColdBoot();

    public BigDecimal getWarmBoot();

    public BigDecimal getAssyToT1();

    public BigDecimal getT2ToPacking();

    public String getFloorName();

    public String getPendingName();

    public BigDecimal getPendingTime();

    public String getBurnIn();

    public BigDecimal getBiTime();

    public BigDecimal getBiTemperature();

    public String getSpeOwnerName();

    public String getEeOwnerName();

    public String getQcOwnerName();

    public String getAssyPackingSop();

    public String getTestSop();

    public Integer getKeypartA();

    public Integer getKeypartB();

    public String getPreAssyName();

    public String getBabFlowName();

    public String getTestFlowName();

    public String getPackingFlowName();

    public Character getPartLink();

    public Integer getCe();

    public Integer getUl();

    public Integer getRohs();

    public Integer getWeee();

    public Integer getMadeInTaiwan();

    public Integer getFcc();

    public Integer getEac();

    public BigDecimal getNsInOneCollectionBox();

    public Character getPartNoAttributeMaintain();

    public Integer getAssyStation();

    public Integer getPackingStation();

    public BigDecimal getAssyLeadTime();

    public BigDecimal getAssyKanbanTime();

    public BigDecimal getPackingLeadTime();

    public BigDecimal getPackingKanbanTime();

    public BigDecimal getCleanPanelAndAssembly();

    public Date getModifiedDate();

}
