package com.advantech.model;
// Generated 2017/3/30 上午 11:57:12 by Hibernate Tools 4.3.1

import com.fasterxml.jackson.annotation.JsonFormat;
import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SheetView generated by hbm2java
 */
@Entity
@Table(name = "Sheet_Main_view",
         schema = "dbo",
         catalog = "E_Document"
)
public class SheetView implements java.io.Serializable {

    private int rowId;
    private BigDecimal assy;
    private BigDecimal assyKanbanTime;
    private BigDecimal assyLeadTime;
    private String assyPackingSop;
    private Integer assyStation;
    private BigDecimal assyToT1;
    private String babFlow;
    private BigDecimal biCost;
    private BigDecimal biTemperature;
    private BigDecimal biTime;
    private String burnIn;
    private String ce;
    private BigDecimal cleanPanel;
    private BigDecimal cleanPanel_and_Assembly;
    private BigDecimal coldBoot;
    private BigDecimal downBiRi;
    private String eac;
    private String eeOwnerId;
    private String eeOwnerName;
    private String fcc;
    private Integer floorId;
    private String floorName;
    private Integer hiPotLeakage;
    private Integer keypartA;
    private Integer keypartB;
    private String madeInTaiwan;
    private String modelName;
    private Date modified_Date;
    private String nInOneCollectionBox;
    private BigDecimal packing;
    private String packingFlow;
    private BigDecimal packingKanbanTime;
    private BigDecimal packingLeadTime;
    private Integer packingStation;
    private String partLink;
    private String partNoAttributeMaintain;
    private String pending;
    private BigDecimal pendingTime;
    private String preAssy;
    private BigDecimal productionWT;
    private String qcOwnerId;
    private String qcOwnerName;
    private String rohs;
    private Integer setupTime;
    private String speOwnerId;
    private String speOwnerName;
    private BigDecimal t1;
    private BigDecimal t2;
    private BigDecimal t2ToPacking;
    private BigDecimal t3;
    private BigDecimal t4;
    private String testFlow;
    private String testSop;
    private BigDecimal totalModule;
    private Integer typeId;
    private String typeName;
    private String ul;
    private BigDecimal upBiRi;
    private Integer vibration;
    private BigDecimal warmBoot;
    private String weee;

    public SheetView() {
    }

    public SheetView(int rowId, String modelName) {
        this.rowId = rowId;
        this.modelName = modelName;
    }

    public SheetView(int rowId, BigDecimal assy, BigDecimal assyKanbanTime, BigDecimal assyLeadTime, String assyPackingSop, Integer assyStation, BigDecimal assyToT1, String babFlow, BigDecimal biCost, BigDecimal biTemperature, BigDecimal biTime, String burnIn, String ce, BigDecimal cleanPanel, BigDecimal cleanPanel_and_Assembly, BigDecimal coldBoot, BigDecimal downBiRi, String eac, String eeOwnerId, String eeOwnerName, String fcc, Integer floorId, String floorName, Integer hiPotLeakage, Integer keypartA, Integer keypartB, String madeInTaiwan, String modelName, Date modified_Date, String nInOneCollectionBox, BigDecimal packing, String packingFlow, BigDecimal packingKanbanTime, BigDecimal packingLeadTime, Integer packingStation, String partLink, String partNoAttributeMaintain, String pending, BigDecimal pendingTime, String preAssy, BigDecimal productionWT, String qcOwnerId, String qcOwnerName, String rohs, Integer setupTime, String speOwnerId, String speOwnerName, BigDecimal t1, BigDecimal t2, BigDecimal t2ToPacking, BigDecimal t3, BigDecimal t4, String testFlow, String testSop, BigDecimal totalModule, Integer typeId, String typeName, String ul, BigDecimal upBiRi, Integer vibration, BigDecimal warmBoot, String weee) {
        this.rowId = rowId;
        this.assy = assy;
        this.assyKanbanTime = assyKanbanTime;
        this.assyLeadTime = assyLeadTime;
        this.assyPackingSop = assyPackingSop;
        this.assyStation = assyStation;
        this.assyToT1 = assyToT1;
        this.babFlow = babFlow;
        this.biCost = biCost;
        this.biTemperature = biTemperature;
        this.biTime = biTime;
        this.burnIn = burnIn;
        this.ce = ce;
        this.cleanPanel = cleanPanel;
        this.cleanPanel_and_Assembly = cleanPanel_and_Assembly;
        this.coldBoot = coldBoot;
        this.downBiRi = downBiRi;
        this.eac = eac;
        this.eeOwnerId = eeOwnerId;
        this.eeOwnerName = eeOwnerName;
        this.fcc = fcc;
        this.floorId = floorId;
        this.floorName = floorName;
        this.hiPotLeakage = hiPotLeakage;
        this.keypartA = keypartA;
        this.keypartB = keypartB;
        this.madeInTaiwan = madeInTaiwan;
        this.modelName = modelName;
        this.modified_Date = modified_Date;
        this.nInOneCollectionBox = nInOneCollectionBox;
        this.packing = packing;
        this.packingFlow = packingFlow;
        this.packingKanbanTime = packingKanbanTime;
        this.packingLeadTime = packingLeadTime;
        this.packingStation = packingStation;
        this.partLink = partLink;
        this.partNoAttributeMaintain = partNoAttributeMaintain;
        this.pending = pending;
        this.pendingTime = pendingTime;
        this.preAssy = preAssy;
        this.productionWT = productionWT;
        this.qcOwnerId = qcOwnerId;
        this.qcOwnerName = qcOwnerName;
        this.rohs = rohs;
        this.setupTime = setupTime;
        this.speOwnerId = speOwnerId;
        this.speOwnerName = speOwnerName;
        this.t1 = t1;
        this.t2 = t2;
        this.t2ToPacking = t2ToPacking;
        this.t3 = t3;
        this.t4 = t4;
        this.testFlow = testFlow;
        this.testSop = testSop;
        this.totalModule = totalModule;
        this.typeId = typeId;
        this.typeName = typeName;
        this.ul = ul;
        this.upBiRi = upBiRi;
        this.vibration = vibration;
        this.warmBoot = warmBoot;
        this.weee = weee;
    }

    @Id
    @Column(name = "rowId", unique = true, nullable = false)
    public int getRowId() {
        return this.rowId;
    }

    public void setRowId(int rowId) {
        this.rowId = rowId;
    }

    @Column(name = "assy", precision = 10, scale = 1)
    public BigDecimal getAssy() {
        return this.assy;
    }

    public void setAssy(BigDecimal assy) {
        this.assy = assy;
    }

    @Column(name = "assyKanbanTime", precision = 10, scale = 1)
    public BigDecimal getAssyKanbanTime() {
        return this.assyKanbanTime;
    }

    public void setAssyKanbanTime(BigDecimal assyKanbanTime) {
        this.assyKanbanTime = assyKanbanTime;
    }

    @Column(name = "assyLeadTime", precision = 10, scale = 1)
    public BigDecimal getAssyLeadTime() {
        return this.assyLeadTime;
    }

    public void setAssyLeadTime(BigDecimal assyLeadTime) {
        this.assyLeadTime = assyLeadTime;
    }

    @Column(name = "assyPackingSop")
    public String getAssyPackingSop() {
        return this.assyPackingSop;
    }

    public void setAssyPackingSop(String assyPackingSop) {
        this.assyPackingSop = assyPackingSop;
    }

    @Column(name = "assyStation")
    public Integer getAssyStation() {
        return this.assyStation;
    }

    public void setAssyStation(Integer assyStation) {
        this.assyStation = assyStation;
    }

    @Column(name = "assyToT1", precision = 10, scale = 1)
    public BigDecimal getAssyToT1() {
        return this.assyToT1;
    }

    public void setAssyToT1(BigDecimal assyToT1) {
        this.assyToT1 = assyToT1;
    }

    @Column(name = "babFlow")
    public String getBabFlow() {
        return this.babFlow;
    }

    public void setBabFlow(String babFlow) {
        this.babFlow = babFlow;
    }

    @Column(name = "biCost", precision = 10, scale = 1)
    public BigDecimal getBiCost() {
        return this.biCost;
    }

    public void setBiCost(BigDecimal biCost) {
        this.biCost = biCost;
    }

    @Column(name = "biTemperature", precision = 10, scale = 1)
    public BigDecimal getBiTemperature() {
        return this.biTemperature;
    }

    public void setBiTemperature(BigDecimal biTemperature) {
        this.biTemperature = biTemperature;
    }

    @Column(name = "biTime", precision = 10, scale = 1)
    public BigDecimal getBiTime() {
        return this.biTime;
    }

    public void setBiTime(BigDecimal biTime) {
        this.biTime = biTime;
    }

    @Column(name = "burnIn")
    public String getBurnIn() {
        return this.burnIn;
    }

    public void setBurnIn(String burnIn) {
        this.burnIn = burnIn;
    }

    @Column(name = "ce")
    public String getCe() {
        return this.ce;
    }

    public void setCe(String ce) {
        this.ce = ce;
    }

    @Column(name = "cleanPanel", precision = 10, scale = 1)
    public BigDecimal getCleanPanel() {
        return this.cleanPanel;
    }

    public void setCleanPanel(BigDecimal cleanPanel) {
        this.cleanPanel = cleanPanel;
    }

    @Column(name = "CleanPanel_and_Assembly", precision = 10, scale = 1)
    public BigDecimal getCleanPanel_and_Assembly() {
        return this.cleanPanel_and_Assembly;
    }

    public void setCleanPanel_and_Assembly(BigDecimal cleanPanel_and_Assembly) {
        this.cleanPanel_and_Assembly = cleanPanel_and_Assembly;
    }

    @Column(name = "coldBoot", precision = 10, scale = 1)
    public BigDecimal getColdBoot() {
        return this.coldBoot;
    }

    public void setColdBoot(BigDecimal coldBoot) {
        this.coldBoot = coldBoot;
    }

    @Column(name = "downBiRi", precision = 10, scale = 1)
    public BigDecimal getDownBiRi() {
        return this.downBiRi;
    }

    public void setDownBiRi(BigDecimal downBiRi) {
        this.downBiRi = downBiRi;
    }

    @Column(name = "eac")
    public String getEac() {
        return this.eac;
    }

    public void setEac(String eac) {
        this.eac = eac;
    }

    @Column(name = "eeOwnerId")
    public String getEeOwnerId() {
        return this.eeOwnerId;
    }

    public void setEeOwnerId(String eeOwnerId) {
        this.eeOwnerId = eeOwnerId;
    }

    @Column(name = "eeOwnerName")
    public String getEeOwnerName() {
        return this.eeOwnerName;
    }

    public void setEeOwnerName(String eeOwnerName) {
        this.eeOwnerName = eeOwnerName;
    }

    @Column(name = "fcc")
    public String getFcc() {
        return this.fcc;
    }

    public void setFcc(String fcc) {
        this.fcc = fcc;
    }

    @Column(name = "floorId")
    public Integer getFloorId() {
        return this.floorId;
    }

    public void setFloorId(Integer floorId) {
        this.floorId = floorId;
    }

    @Column(name = "floorName")
    public String getFloorName() {
        return this.floorName;
    }

    public void setFloorName(String floorName) {
        this.floorName = floorName;
    }

    @Column(name = "hiPotLeakage")
    public Integer getHiPotLeakage() {
        return this.hiPotLeakage;
    }

    public void setHiPotLeakage(Integer hiPotLeakage) {
        this.hiPotLeakage = hiPotLeakage;
    }

    @Column(name = "keypartA")
    public Integer getKeypartA() {
        return this.keypartA;
    }

    public void setKeypartA(Integer keypartA) {
        this.keypartA = keypartA;
    }

    @Column(name = "keypartB")
    public Integer getKeypartB() {
        return this.keypartB;
    }

    public void setKeypartB(Integer keypartB) {
        this.keypartB = keypartB;
    }

    @Column(name = "madeInTaiwan")
    public String getMadeInTaiwan() {
        return this.madeInTaiwan;
    }

    public void setMadeInTaiwan(String madeInTaiwan) {
        this.madeInTaiwan = madeInTaiwan;
    }

    @Column(name = "modelName", nullable = false, length = 50)
    public String getModelName() {
        return this.modelName;
    }

    public void setModelName(String modelName) {
        this.modelName = modelName;
    }

    @JsonFormat(pattern = "yyyy-MM-dd'T'kk:mm:ss.SSS'Z'", timezone="GMT+8")
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "Modified_Date", updatable = false, length = 23)
    public Date getModified_Date() {
        return this.modified_Date;
    }

    public void setModified_Date(Date modified_Date) {
        this.modified_Date = modified_Date;
    }

    @Column(name = "n_in_one_collection_box")
    public String getnInOneCollectionBox() {
        return this.nInOneCollectionBox;
    }

    public void setnInOneCollectionBox(String nInOneCollectionBox) {
        this.nInOneCollectionBox = nInOneCollectionBox;
    }

    @Column(name = "packing", precision = 10, scale = 1)
    public BigDecimal getPacking() {
        return this.packing;
    }

    public void setPacking(BigDecimal packing) {
        this.packing = packing;
    }

    @Column(name = "packingFlow")
    public String getPackingFlow() {
        return this.packingFlow;
    }

    public void setPackingFlow(String packingFlow) {
        this.packingFlow = packingFlow;
    }

    @Column(name = "packingKanbanTime", precision = 10, scale = 1)
    public BigDecimal getPackingKanbanTime() {
        return this.packingKanbanTime;
    }

    public void setPackingKanbanTime(BigDecimal packingKanbanTime) {
        this.packingKanbanTime = packingKanbanTime;
    }

    @Column(name = "packingLeadTime", precision = 10, scale = 1)
    public BigDecimal getPackingLeadTime() {
        return this.packingLeadTime;
    }

    public void setPackingLeadTime(BigDecimal packingLeadTime) {
        this.packingLeadTime = packingLeadTime;
    }

    @Column(name = "packingStation")
    public Integer getPackingStation() {
        return this.packingStation;
    }

    public void setPackingStation(Integer packingStation) {
        this.packingStation = packingStation;
    }

    @Column(name = "partLink")
    public String getPartLink() {
        return this.partLink;
    }

    public void setPartLink(String partLink) {
        this.partLink = partLink;
    }

    @Column(name = "partNoAttributeMaintain")
    public String getPartNoAttributeMaintain() {
        return this.partNoAttributeMaintain;
    }

    public void setPartNoAttributeMaintain(String partNoAttributeMaintain) {
        this.partNoAttributeMaintain = partNoAttributeMaintain;
    }

    @Column(name = "pending")
    public String getPending() {
        return this.pending;
    }

    public void setPending(String pending) {
        this.pending = pending;
    }

    @Column(name = "pendingTime", precision = 10, scale = 1)
    public BigDecimal getPendingTime() {
        return this.pendingTime;
    }

    public void setPendingTime(BigDecimal pendingTime) {
        this.pendingTime = pendingTime;
    }

    @Column(name = "preAssy")
    public String getPreAssy() {
        return this.preAssy;
    }

    public void setPreAssy(String preAssy) {
        this.preAssy = preAssy;
    }

    @Column(name = "ProductionWT", precision = 10, scale = 1)
    public BigDecimal getProductionWT() {
        return this.productionWT;
    }

    public void setProductionWT(BigDecimal productionWT) {
        this.productionWT = productionWT;
    }

    @Column(name = "qcOwnerId")
    public String getQcOwnerId() {
        return this.qcOwnerId;
    }

    public void setQcOwnerId(String qcOwnerId) {
        this.qcOwnerId = qcOwnerId;
    }

    @Column(name = "qcOwnerName")
    public String getQcOwnerName() {
        return this.qcOwnerName;
    }

    public void setQcOwnerName(String qcOwnerName) {
        this.qcOwnerName = qcOwnerName;
    }

    @Column(name = "rohs")
    public String getRohs() {
        return this.rohs;
    }

    public void setRohs(String rohs) {
        this.rohs = rohs;
    }

    @Column(name = "SetupTime")
    public Integer getSetupTime() {
        return this.setupTime;
    }

    public void setSetupTime(Integer setupTime) {
        this.setupTime = setupTime;
    }

    @Column(name = "speOwnerId")
    public String getSpeOwnerId() {
        return this.speOwnerId;
    }

    public void setSpeOwnerId(String speOwnerId) {
        this.speOwnerId = speOwnerId;
    }

    @Column(name = "speOwnerName")
    public String getSpeOwnerName() {
        return this.speOwnerName;
    }

    public void setSpeOwnerName(String speOwnerName) {
        this.speOwnerName = speOwnerName;
    }

    @Column(name = "t1", precision = 10, scale = 1)
    public BigDecimal getT1() {
        return this.t1;
    }

    public void setT1(BigDecimal t1) {
        this.t1 = t1;
    }

    @Column(name = "t2", precision = 10, scale = 1)
    public BigDecimal getT2() {
        return this.t2;
    }

    public void setT2(BigDecimal t2) {
        this.t2 = t2;
    }

    @Column(name = "t2ToPacking", precision = 10, scale = 1)
    public BigDecimal getT2ToPacking() {
        return this.t2ToPacking;
    }

    public void setT2ToPacking(BigDecimal t2ToPacking) {
        this.t2ToPacking = t2ToPacking;
    }

    @Column(name = "t3", precision = 10, scale = 1)
    public BigDecimal getT3() {
        return this.t3;
    }

    public void setT3(BigDecimal t3) {
        this.t3 = t3;
    }

    @Column(name = "t4", precision = 10, scale = 1)
    public BigDecimal getT4() {
        return this.t4;
    }

    public void setT4(BigDecimal t4) {
        this.t4 = t4;
    }

    @Column(name = "testFlow")
    public String getTestFlow() {
        return this.testFlow;
    }

    public void setTestFlow(String testFlow) {
        this.testFlow = testFlow;
    }

    @Column(name = "testSop")
    public String getTestSop() {
        return this.testSop;
    }

    public void setTestSop(String testSop) {
        this.testSop = testSop;
    }

    @Column(name = "totalModule", precision = 10, scale = 1)
    public BigDecimal getTotalModule() {
        return this.totalModule;
    }

    public void setTotalModule(BigDecimal totalModule) {
        this.totalModule = totalModule;
    }

    @Column(name = "typeId")
    public Integer getTypeId() {
        return this.typeId;
    }

    public void setTypeId(Integer typeId) {
        this.typeId = typeId;
    }

    @Column(name = "typeName")
    public String getTypeName() {
        return this.typeName;
    }

    public void setTypeName(String typeName) {
        this.typeName = typeName;
    }

    @Column(name = "ul")
    public String getUl() {
        return this.ul;
    }

    public void setUl(String ul) {
        this.ul = ul;
    }

    @Column(name = "upBiRi", precision = 10, scale = 1)
    public BigDecimal getUpBiRi() {
        return this.upBiRi;
    }

    public void setUpBiRi(BigDecimal upBiRi) {
        this.upBiRi = upBiRi;
    }

    @Column(name = "vibration")
    public Integer getVibration() {
        return this.vibration;
    }

    public void setVibration(Integer vibration) {
        this.vibration = vibration;
    }

    @Column(name = "warmBoot", precision = 10, scale = 1)
    public BigDecimal getWarmBoot() {
        return this.warmBoot;
    }

    public void setWarmBoot(BigDecimal warmBoot) {
        this.warmBoot = warmBoot;
    }

    @Column(name = "weee")
    public String getWeee() {
        return this.weee;
    }

    public void setWeee(String weee) {
        this.weee = weee;
    }

}
