package com.advantech.model;
// Generated 2017/3/30 下午 01:07:49 by Hibernate Tools 4.3.1

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;
import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SheetSpe generated by hbm2java
 */
@Entity
@Table(name = "Sheet_SPE",
         schema = "dbo",
         catalog = "E_Document"
)
@JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class, property = "id")
public class SheetSpe implements java.io.Serializable {

    private int id;
    private Floor floor;
    private Identit identitByEeOwnerId;
    private Identit identitBySpeOwnerId;
    private Identit identitByQcOwnerId;
    private Model model;
    private Type type;
    private BigDecimal cleanPanel;
    private BigDecimal assy;
    private BigDecimal packing;
    private BigDecimal biCost;
    private Integer vibration;
    private Integer hiPotLeakage;
    private BigDecimal coldBoot;
    private BigDecimal warmBoot;
    private BigDecimal assyToT1;
    private BigDecimal t2ToPacking;
    private String pending;
    private BigDecimal pendingTime;
    private String burnIn;
    private BigDecimal biTime;
    private BigDecimal biTemperature;
    private String assyPackingSop;
    private Integer keypartA;
    private Integer keypartB;
    private String preAssy;
    private String babFlow;
    private String testFlow;
    private String packingFlow;
    private String partLink;
    private String NIn1CollectionBox;
    private String partNoAttrMaintain;
    private BigDecimal t1;
    private BigDecimal t2;
    private BigDecimal t3;
    private BigDecimal t4;
    private BigDecimal upBiRi;
    private BigDecimal downBiRi;
    private String testSop;
    private Date modifiedDate;

    @JsonIgnore
    private Set<LabelInfo> labelInfos = new HashSet<LabelInfo>(0);

    public SheetSpe() {
    }

    public SheetSpe(int id) {
        this.id = id;
    }

    public SheetSpe(int id, Floor floor, Identit identitByEeOwnerId, Identit identitBySpeOwnerId, Identit identitByQcOwnerId, Model model, Type type, BigDecimal cleanPanel, BigDecimal assy, BigDecimal packing, BigDecimal biCost, Integer vibration, Integer hiPotLeakage, BigDecimal coldBoot, BigDecimal warmBoot, BigDecimal assyToT1, BigDecimal t2ToPacking, String pending, BigDecimal pendingTime, String burnIn, BigDecimal biTime, BigDecimal biTemperature, String assyPackingSop, Integer keypartA, Integer keypartB, String preAssy, String babFlow, String testFlow, String packingFlow, String partLink, String NIn1CollectionBox, String partNoAttrMaintain, BigDecimal t1, BigDecimal t2, BigDecimal t3, BigDecimal t4, BigDecimal upBiRi, BigDecimal downBiRi, String testSop, Date modifiedDate, Set<LabelInfo> labelInfos) {
        this.id = id;
        this.floor = floor;
        this.identitByEeOwnerId = identitByEeOwnerId;
        this.identitBySpeOwnerId = identitBySpeOwnerId;
        this.identitByQcOwnerId = identitByQcOwnerId;
        this.model = model;
        this.type = type;
        this.cleanPanel = cleanPanel;
        this.assy = assy;
        this.packing = packing;
        this.biCost = biCost;
        this.vibration = vibration;
        this.hiPotLeakage = hiPotLeakage;
        this.coldBoot = coldBoot;
        this.warmBoot = warmBoot;
        this.assyToT1 = assyToT1;
        this.t2ToPacking = t2ToPacking;
        this.pending = pending;
        this.pendingTime = pendingTime;
        this.burnIn = burnIn;
        this.biTime = biTime;
        this.biTemperature = biTemperature;
        this.assyPackingSop = assyPackingSop;
        this.keypartA = keypartA;
        this.keypartB = keypartB;
        this.preAssy = preAssy;
        this.babFlow = babFlow;
        this.testFlow = testFlow;
        this.packingFlow = packingFlow;
        this.partLink = partLink;
        this.NIn1CollectionBox = NIn1CollectionBox;
        this.partNoAttrMaintain = partNoAttrMaintain;
        this.t1 = t1;
        this.t2 = t2;
        this.t3 = t3;
        this.t4 = t4;
        this.upBiRi = upBiRi;
        this.downBiRi = downBiRi;
        this.testSop = testSop;
        this.modifiedDate = modifiedDate;
        this.labelInfos = labelInfos;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "Floor_id")
    public Floor getFloor() {
        return this.floor;
    }

    public void setFloor(Floor floor) {
        this.floor = floor;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "EE_owner_id")
    public Identit getIdentitByEeOwnerId() {
        return this.identitByEeOwnerId;
    }

    public void setIdentitByEeOwnerId(Identit identitByEeOwnerId) {
        this.identitByEeOwnerId = identitByEeOwnerId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "SPE_owner_id")
    public Identit getIdentitBySpeOwnerId() {
        return this.identitBySpeOwnerId;
    }

    public void setIdentitBySpeOwnerId(Identit identitBySpeOwnerId) {
        this.identitBySpeOwnerId = identitBySpeOwnerId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "QC_owner_id")
    public Identit getIdentitByQcOwnerId() {
        return this.identitByQcOwnerId;
    }

    public void setIdentitByQcOwnerId(Identit identitByQcOwnerId) {
        this.identitByQcOwnerId = identitByQcOwnerId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "Model_id")
    public Model getModel() {
        return this.model;
    }

    public void setModel(Model model) {
        this.model = model;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "Type_id")
    public Type getType() {
        return this.type;
    }

    public void setType(Type type) {
        this.type = type;
    }

    @Column(name = "CleanPanel", precision = 10, scale = 1)
    public BigDecimal getCleanPanel() {
        return this.cleanPanel;
    }

    public void setCleanPanel(BigDecimal cleanPanel) {
        this.cleanPanel = cleanPanel;
    }

    @Column(name = "ASSY", precision = 10, scale = 1)
    public BigDecimal getAssy() {
        return this.assy;
    }

    public void setAssy(BigDecimal assy) {
        this.assy = assy;
    }

    @Column(name = "Packing", precision = 10, scale = 1)
    public BigDecimal getPacking() {
        return this.packing;
    }

    public void setPacking(BigDecimal packing) {
        this.packing = packing;
    }

    @Column(name = "BI_Cost", precision = 10, scale = 1)
    public BigDecimal getBiCost() {
        return this.biCost;
    }

    public void setBiCost(BigDecimal biCost) {
        this.biCost = biCost;
    }

    @Column(name = "Vibration")
    public Integer getVibration() {
        return this.vibration;
    }

    public void setVibration(Integer vibration) {
        this.vibration = vibration;
    }

    @Column(name = "Hi_Pot_Leakage")
    public Integer getHiPotLeakage() {
        return this.hiPotLeakage;
    }

    public void setHiPotLeakage(Integer hiPotLeakage) {
        this.hiPotLeakage = hiPotLeakage;
    }

    @Column(name = "Cold_Boot", precision = 10, scale = 1)
    public BigDecimal getColdBoot() {
        return this.coldBoot;
    }

    public void setColdBoot(BigDecimal coldBoot) {
        this.coldBoot = coldBoot;
    }

    @Column(name = "Warm_Boot", precision = 10, scale = 1)
    public BigDecimal getWarmBoot() {
        return this.warmBoot;
    }

    public void setWarmBoot(BigDecimal warmBoot) {
        this.warmBoot = warmBoot;
    }

    @Column(name = "ASSY_to_T1", precision = 10, scale = 1)
    public BigDecimal getAssyToT1() {
        return this.assyToT1;
    }

    public void setAssyToT1(BigDecimal assyToT1) {
        this.assyToT1 = assyToT1;
    }

    @Column(name = "T2_to_Packing", precision = 10, scale = 1)
    public BigDecimal getT2ToPacking() {
        return this.t2ToPacking;
    }

    public void setT2ToPacking(BigDecimal t2ToPacking) {
        this.t2ToPacking = t2ToPacking;
    }

    @Column(name = "Pending", length = 50)
    public String getPending() {
        return this.pending;
    }

    public void setPending(String pending) {
        this.pending = pending;
    }

    @Column(name = "Pending_Time", precision = 10, scale = 1)
    public BigDecimal getPendingTime() {
        return this.pendingTime;
    }

    public void setPendingTime(BigDecimal pendingTime) {
        this.pendingTime = pendingTime;
    }

    @Column(name = "BurnIn", length = 10)
    public String getBurnIn() {
        return this.burnIn;
    }

    public void setBurnIn(String burnIn) {
        this.burnIn = burnIn;
    }

    @Column(name = "BI_Time", precision = 10, scale = 1)
    public BigDecimal getBiTime() {
        return this.biTime;
    }

    public void setBiTime(BigDecimal biTime) {
        this.biTime = biTime;
    }

    @Column(name = "BI_Temperature", precision = 10, scale = 1)
    public BigDecimal getBiTemperature() {
        return this.biTemperature;
    }

    public void setBiTemperature(BigDecimal biTemperature) {
        this.biTemperature = biTemperature;
    }

    @Column(name = "ASSY_Packing_SOP", length = 500)
    public String getAssyPackingSop() {
        return this.assyPackingSop;
    }

    public void setAssyPackingSop(String assyPackingSop) {
        this.assyPackingSop = assyPackingSop;
    }

    @Column(name = "Keypart_A")
    public Integer getKeypartA() {
        return this.keypartA;
    }

    public void setKeypartA(Integer keypartA) {
        this.keypartA = keypartA;
    }

    @Column(name = "Keypart_B")
    public Integer getKeypartB() {
        return this.keypartB;
    }

    public void setKeypartB(Integer keypartB) {
        this.keypartB = keypartB;
    }

    @Column(name = "Pre_ASSY", length = 50)
    public String getPreAssy() {
        return this.preAssy;
    }

    public void setPreAssy(String preAssy) {
        this.preAssy = preAssy;
    }

    @Column(name = "BAB_Flow", length = 100)
    public String getBabFlow() {
        return this.babFlow;
    }

    public void setBabFlow(String babFlow) {
        this.babFlow = babFlow;
    }

    @Column(name = "Test_Flow", length = 100)
    public String getTestFlow() {
        return this.testFlow;
    }

    public void setTestFlow(String testFlow) {
        this.testFlow = testFlow;
    }

    @Column(name = "Packing_Flow", length = 50)
    public String getPackingFlow() {
        return this.packingFlow;
    }

    public void setPackingFlow(String packingFlow) {
        this.packingFlow = packingFlow;
    }

    @Column(name = "Part_Link", length = 50)
    public String getPartLink() {
        return this.partLink;
    }

    public void setPartLink(String partLink) {
        this.partLink = partLink;
    }

    @Column(name = "N_In_1_collection_box", length = 50)
    public String getNIn1CollectionBox() {
        return this.NIn1CollectionBox;
    }

    public void setNIn1CollectionBox(String NIn1CollectionBox) {
        this.NIn1CollectionBox = NIn1CollectionBox;
    }

    @Column(name = "PartNo_attr_maintain", length = 50)
    public String getPartNoAttrMaintain() {
        return this.partNoAttrMaintain;
    }

    public void setPartNoAttrMaintain(String partNoAttrMaintain) {
        this.partNoAttrMaintain = partNoAttrMaintain;
    }

    @Column(name = "T1", precision = 10, scale = 1)
    public BigDecimal getT1() {
        return this.t1;
    }

    public void setT1(BigDecimal t1) {
        this.t1 = t1;
    }

    @Column(name = "T2", precision = 10, scale = 1)
    public BigDecimal getT2() {
        return this.t2;
    }

    public void setT2(BigDecimal t2) {
        this.t2 = t2;
    }

    @Column(name = "T3", precision = 10, scale = 1)
    public BigDecimal getT3() {
        return this.t3;
    }

    public void setT3(BigDecimal t3) {
        this.t3 = t3;
    }

    @Column(name = "T4", precision = 10, scale = 1)
    public BigDecimal getT4() {
        return this.t4;
    }

    public void setT4(BigDecimal t4) {
        this.t4 = t4;
    }

    @Column(name = "Up_BI_RI", precision = 10, scale = 1)
    public BigDecimal getUpBiRi() {
        return this.upBiRi;
    }

    public void setUpBiRi(BigDecimal upBiRi) {
        this.upBiRi = upBiRi;
    }

    @Column(name = "Down_BI_RI", precision = 10, scale = 1)
    public BigDecimal getDownBiRi() {
        return this.downBiRi;
    }

    public void setDownBiRi(BigDecimal downBiRi) {
        this.downBiRi = downBiRi;
    }

    @Column(name = "Test_SOP", length = 500)
    public String getTestSop() {
        return this.testSop;
    }

    public void setTestSop(String testSop) {
        this.testSop = testSop;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "Modified_Date", length = 23, updatable = false)
    public Date getModifiedDate() {
        return this.modifiedDate;
    }

    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "sheetSpe")
    public Set<LabelInfo> getLabelInfos() {
        return this.labelInfos;
    }

    public void setLabelInfos(Set<LabelInfo> labelInfos) {
        this.labelInfos = labelInfos;
    }

}
