package com.advantech.model;
// Generated 2017/5/25 上午 10:45:32 by Hibernate Tools 4.3.1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * BabTagNameComparison generated by hbm2java
 */
@Entity
@Table(name = "LS_TagNameComparison")
public class TagNameComparison implements java.io.Serializable {

    private TagNameComparisonId id;
    private Line line;
    private int position;

    public TagNameComparison() {
    }

    public TagNameComparison(TagNameComparisonId id) {
        this.id = id;
    }

    @EmbeddedId
    @AttributeOverrides({
        @AttributeOverride(name = "orginTagName", column = @Column(name = "orginTagName", nullable = false, length = 50))
        , 
        @AttributeOverride(name = "lampSysTagName", column = @Column(name = "lampSysTagName", nullable = false, length = 50))
    })
    public TagNameComparisonId getId() {
        return this.id;
    }

    public void setId(TagNameComparisonId id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "line_id")
    public Line getLine() {
        return this.line;
    }

    public void setLine(Line line) {
        this.line = line;
    }

    @Column(name = "position")
    public int getPosition() {
        return this.position;
    }

    public void setPosition(int position) {
        this.position = position;
    }

}
