package com.advantech.model;
// Generated 2017/5/25 上午 10:45:32 by Hibernate Tools 4.3.1

import javax.persistence.Embeddable;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;

/**
 * LsTagNameComparisonId generated by hbm2java
 */
@Embeddable
public class TagNameComparisonId implements java.io.Serializable {

    private Sensor orginTagName;
    private SensorTransform lampSysTagName;

    public TagNameComparisonId() {
    }

    public TagNameComparisonId(Sensor orginTagName, SensorTransform lampSysTagName) {
        this.orginTagName = orginTagName;
        this.lampSysTagName = lampSysTagName;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "orginTagName", nullable = false)
    public Sensor getOrginTagName() {
        return this.orginTagName;
    }

    public void setOrginTagName(Sensor orginTagName) {
        this.orginTagName = orginTagName;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "lampSysTagName", nullable = false)
    public SensorTransform getLampSysTagName() {
        return this.lampSysTagName;
    }

    public void setLampSysTagName(SensorTransform lampSysTagName) {
        this.lampSysTagName = lampSysTagName;
    }

    @Override
    public boolean equals(Object other) {
        if ((this == other)) {
            return true;
        }
        if ((other == null)) {
            return false;
        }
        if (!(other instanceof TagNameComparisonId)) {
            return false;
        }
        TagNameComparisonId castOther = (TagNameComparisonId) other;

        return ((this.getOrginTagName() == null ? castOther.getOrginTagName() == null : this.getOrginTagName().equals(castOther.getOrginTagName())) || (this.getOrginTagName() != null && castOther.getOrginTagName() != null && this.getOrginTagName().equals(castOther.getOrginTagName())))
                && ((this.getLampSysTagName() == null ? castOther.getLampSysTagName() == null : this.getLampSysTagName().equals(castOther.getLampSysTagName())) || (this.getLampSysTagName() != null && castOther.getLampSysTagName() != null && this.getLampSysTagName().equals(castOther.getLampSysTagName())));
    }

    @Override
    public int hashCode() {
        int result = 17;

        result = 37 * result + (getOrginTagName() == null ? 0 : this.getOrginTagName().hashCode());
        result = 37 * result + (getLampSysTagName() == null ? 0 : this.getLampSysTagName().hashCode());
        return result;
    }

}
