package com.advantech.model;
// Generated 2017/5/25 上午 10:45:32 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * LsTagNameComparisonId generated by hbm2java
 */
@Embeddable
public class TagNameComparisonId implements java.io.Serializable {

    private String orginTagName;
    private String lampSysTagName;

    public TagNameComparisonId() {
    }

    public TagNameComparisonId(String orginTagName, String lampSysTagName) {
        this.orginTagName = orginTagName;
        this.lampSysTagName = lampSysTagName;
    }

    @Column(name = "orginTagName", nullable = false, length = 50)
    public String getOrginTagName() {
        return this.orginTagName;
    }

    public void setOrginTagName(String orginTagName) {
        this.orginTagName = orginTagName;
    }

    @Column(name = "lampSysTagName", nullable = false, length = 50)
    public String getLampSysTagName() {
        return this.lampSysTagName;
    }

    public void setLampSysTagName(String lampSysTagName) {
        this.lampSysTagName = lampSysTagName;
    }

    @Override
    public boolean equals(Object other) {
        if ((this == other)) {
            return true;
        }
        if ((other == null)) {
            return false;
        }
        if (!(other instanceof TagNameComparisonId)) {
            return false;
        }
        TagNameComparisonId castOther = (TagNameComparisonId) other;

        return ((this.getOrginTagName() == null ? castOther.getOrginTagName() == null : this.getOrginTagName().equals(castOther.getOrginTagName())) || (this.getOrginTagName() != null && castOther.getOrginTagName() != null && this.getOrginTagName().equals(castOther.getOrginTagName())))
                && ((this.getLampSysTagName() == null ? castOther.getLampSysTagName() == null : this.getLampSysTagName().equals(castOther.getLampSysTagName())) || (this.getLampSysTagName() != null && castOther.getLampSysTagName() != null && this.getLampSysTagName().equals(castOther.getLampSysTagName())));
    }

    @Override
    public int hashCode() {
        int result = 17;

        result = 37 * result + (getOrginTagName() == null ? 0 : this.getOrginTagName().hashCode());
        result = 37 * result + (getLampSysTagName() == null ? 0 : this.getLampSysTagName().hashCode());
        return result;
    }

}
