package com.advantech.model;
// Generated 2017/3/15 上午 09:14:05 by Hibernate Tools 4.3.1

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Type generated by hbm2java
 */
@Entity
@Table(name = "Type",
        schema = "dbo",
        catalog = "E_Document"
)
@JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class, property = "id")
public class Type implements java.io.Serializable {

    private int id;
    private String name;

    @JsonIgnore
    private Set<SheetSpe> sheetSpes = new HashSet<SheetSpe>(0);

    public Type() {
    }

    public Type(int id, String name) {
        this.id = id;
        this.name = name;
    }

    public Type(int id, String name, Set<SheetSpe> sheetSpes) {
        this.id = id;
        this.name = name;
        this.sheetSpes = sheetSpes;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @Column(name = "name", nullable = false, length = 50)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "type")
    public Set<SheetSpe> getSheetSpes() {
        return this.sheetSpes;
    }

    public void setSheetSpes(Set<SheetSpe> sheetSpes) {
        this.sheetSpes = sheetSpes;
    }

}
