package com.advantech.model;
// Generated 2017/4/6 下午 02:45:49 by Hibernate Tools 4.3.1

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;
import java.sql.Clob;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * WorktimeColumnGroup generated by hbm2java
 */
@Entity
@Table(name = "Worktime_ColumnGroup",
         schema = "dbo",
         catalog = "E_Document"
)
@JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class, property = "id")
public class WorktimeColumnGroup implements java.io.Serializable {

    private int id;
    private UserType userType;
    private Clob columnName;

    public WorktimeColumnGroup() {
    }

    public WorktimeColumnGroup(int id) {
        this.id = id;
    }

    public WorktimeColumnGroup(int id, UserType userType, Clob columnName) {
        this.id = id;
        this.userType = userType;
        this.columnName = columnName;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "userType_id")
    public UserType getUserType() {
        return this.userType;
    }

    public void setUserType(UserType userType) {
        this.userType = userType;
    }

    @Column(name = "column_name")
    public Clob getColumnName() {
        return this.columnName;
    }

    public void setColumnName(Clob columnName) {
        this.columnName = columnName;
    }

}
