package com.advantech.entity;
// Generated 2017/3/13 上午 09:50:39 by Hibernate Tools 4.3.1

import com.fasterxml.jackson.annotation.JsonManagedReference;
import com.google.gson.annotations.Expose;
import java.util.HashSet;
import java.util.Set;

/**
 * Floor generated by hbm2java
 */

public class Floor implements java.io.Serializable {

    @Expose
    private int id;

    @Expose
    private String name;

    @JsonManagedReference
    private Set identits = new HashSet(0);

    @JsonManagedReference
    private Set sheetSpes = new HashSet(0);

    public Floor() {
    }

    public Floor(int id, String name) {
        this.id = id;
        this.name = name;
    }

    public Floor(int id, String name, Set identits, Set sheetSpes) {
        this.id = id;
        this.name = name;
        this.identits = identits;
        this.sheetSpes = sheetSpes;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Set getIdentits() {
        return this.identits;
    }

    public void setIdentits(Set identits) {
        this.identits = identits;
    }

    public Set getSheetSpes() {
        return this.sheetSpes;
    }

    public void setSheetSpes(Set sheetSpes) {
        this.sheetSpes = sheetSpes;
    }

}
