package com.advantech.entity;
// Generated 2017/3/13 上午 09:50:39 by Hibernate Tools 4.3.1

import com.fasterxml.jackson.annotation.JsonBackReference;


/**s
 * Identit generated by hbm2java
 */

public class Identit implements java.io.Serializable {

    private int id;

    @JsonBackReference
    private Floor floor;

    @JsonBackReference
    private UserType userType;

    private String jobnumber;

    private String password;

    private String name;

    private Integer permission;

    private String email;

    public Identit() {
    }

    public Identit(int id) {
        this.id = id;
    }

    public Identit(int id, Floor floor, UserType userType, String jobnumber, String password, String name, Integer permission, String email) {
        this.id = id;
        this.floor = floor;
        this.userType = userType;
        this.jobnumber = jobnumber;
        this.password = password;
        this.name = name;
        this.permission = permission;
        this.email = email;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public Floor getFloor() {
        return this.floor;
    }

    public void setFloor(Floor floor) {
        this.floor = floor;
    }

    public UserType getUserType() {
        return this.userType;
    }

    public void setUserType(UserType userType) {
        this.userType = userType;
    }

    public String getJobnumber() {
        return this.jobnumber;
    }

    public void setJobnumber(String jobnumber) {
        this.jobnumber = jobnumber;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getPermission() {
        return this.permission;
    }

    public void setPermission(Integer permission) {
        this.permission = permission;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

}
