package com.advantech.entity;
// Generated 2017/3/13 上午 09:50:39 by Hibernate Tools 4.3.1

import com.google.gson.annotations.Expose;

/**
 * LabelInfo generated by hbm2java
 */
public class LabelInfo implements java.io.Serializable {

    @Expose
    private int id;
    @Expose
    private SheetSpe sheetSpe;
    @Expose
    private String ce;
    @Expose
    private String ul;
    @Expose
    private String rohs;
    @Expose
    private String weee;
    @Expose
    private String madeInTaiwan;
    @Expose
    private String fcc;
    @Expose
    private String eac;

    public LabelInfo() {
    }

    public LabelInfo(int id) {
        this.id = id;
    }

    public LabelInfo(int id, SheetSpe sheetSpe, String ce, String ul, String rohs, String weee, String madeInTaiwan, String fcc, String eac) {
        this.id = id;
        this.sheetSpe = sheetSpe;
        this.ce = ce;
        this.ul = ul;
        this.rohs = rohs;
        this.weee = weee;
        this.madeInTaiwan = madeInTaiwan;
        this.fcc = fcc;
        this.eac = eac;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public SheetSpe getSheetSpe() {
        return this.sheetSpe;
    }

    public void setSheetSpe(SheetSpe sheetSpe) {
        this.sheetSpe = sheetSpe;
    }

    public String getCe() {
        return this.ce;
    }

    public void setCe(String ce) {
        this.ce = ce;
    }

    public String getUl() {
        return this.ul;
    }

    public void setUl(String ul) {
        this.ul = ul;
    }

    public String getRohs() {
        return this.rohs;
    }

    public void setRohs(String rohs) {
        this.rohs = rohs;
    }

    public String getWeee() {
        return this.weee;
    }

    public void setWeee(String weee) {
        this.weee = weee;
    }

    public String getMadeInTaiwan() {
        return this.madeInTaiwan;
    }

    public void setMadeInTaiwan(String madeInTaiwan) {
        this.madeInTaiwan = madeInTaiwan;
    }

    public String getFcc() {
        return this.fcc;
    }

    public void setFcc(String fcc) {
        this.fcc = fcc;
    }

    public String getEac() {
        return this.eac;
    }

    public void setEac(String eac) {
        this.eac = eac;
    }

}
