package com.advantech.entity;
// Generated 2017/3/13 上午 09:50:39 by Hibernate Tools 4.3.1

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonManagedReference;
import com.google.gson.annotations.Expose;
import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * SheetSpe generated by hbm2java
 */
public class SheetSpe implements java.io.Serializable {

    @Expose
    private int id;

    @Expose
    @JsonBackReference
    private Floor floor;

    @Expose
    @JsonBackReference
    private Model model;

    @Expose
    @JsonBackReference
    private Type type;

    @Expose
    private BigDecimal cleanPanel;

    @Expose
    private BigDecimal assy;

    @Expose
    private BigDecimal packing;

    @Expose
    private BigDecimal biCost;

    @Expose
    private Integer vibration;

    @Expose
    private Integer hiPotLeakage;

    @Expose
    private BigDecimal coldBoot;

    @Expose
    private BigDecimal warmBoot;

    @Expose
    private BigDecimal assyToT1;

    @Expose
    private BigDecimal t2ToPacking;

    @Expose
    private String burnIn;

    @Expose
    private BigDecimal biTime;

    @Expose
    private BigDecimal biTemperature;

    @Expose
    private Integer speOwnerId;

    @Expose
    private Integer eeOwnerId;
    @Expose
    private Integer qcOwnerId;

    @Expose
    private String assyPackingSop;

    @Expose
    private Integer keypartA;

    @Expose
    private Integer keypartB;

    @Expose
    private String preAssy;

    @Expose
    private String babFlow;

    @Expose
    private String testFlow;

    @Expose
    private String packingFlow;

    @Expose
    private String partLink;

    @Expose
    private String NIn1CollectionBox;

    @Expose
    private String partNoAttrMaintain;

    @Expose
    private Date modifiedDate;

    @JsonManagedReference
    private Set labelInfos = new HashSet(0);

    @JsonManagedReference
    private Set pendings = new HashSet(0);

    public SheetSpe() {
    }

    public SheetSpe(int id) {
        this.id = id;
    }

    public SheetSpe(int id, Floor floor, Model model, Type type, BigDecimal cleanPanel, BigDecimal assy, BigDecimal packing, BigDecimal biCost, Integer vibration, Integer hiPotLeakage, BigDecimal coldBoot, BigDecimal warmBoot, BigDecimal assyToT1, BigDecimal t2ToPacking, String burnIn, BigDecimal biTime, BigDecimal biTemperature, Integer speOwnerId, Integer eeOwnerId, Integer qcOwnerId, String assyPackingSop, Integer keypartA, Integer keypartB, String preAssy, String babFlow, String testFlow, String packingFlow, String partLink, String NIn1CollectionBox, String partNoAttrMaintain, Date modifiedDate, Set labelInfos, Set pendings) {
        this.id = id;
        this.floor = floor;
        this.model = model;
        this.type = type;
        this.cleanPanel = cleanPanel;
        this.assy = assy;
        this.packing = packing;
        this.biCost = biCost;
        this.vibration = vibration;
        this.hiPotLeakage = hiPotLeakage;
        this.coldBoot = coldBoot;
        this.warmBoot = warmBoot;
        this.assyToT1 = assyToT1;
        this.t2ToPacking = t2ToPacking;
        this.burnIn = burnIn;
        this.biTime = biTime;
        this.biTemperature = biTemperature;
        this.speOwnerId = speOwnerId;
        this.eeOwnerId = eeOwnerId;
        this.qcOwnerId = qcOwnerId;
        this.assyPackingSop = assyPackingSop;
        this.keypartA = keypartA;
        this.keypartB = keypartB;
        this.preAssy = preAssy;
        this.babFlow = babFlow;
        this.testFlow = testFlow;
        this.packingFlow = packingFlow;
        this.partLink = partLink;
        this.NIn1CollectionBox = NIn1CollectionBox;
        this.partNoAttrMaintain = partNoAttrMaintain;
        this.modifiedDate = modifiedDate;
        this.labelInfos = labelInfos;
        this.pendings = pendings;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public Floor getFloor() {
        return this.floor;
    }

    public void setFloor(Floor floor) {
        this.floor = floor;
    }

    public Model getModel() {
        return this.model;
    }

    public void setModel(Model model) {
        this.model = model;
    }

    public Type getType() {
        return this.type;
    }

    public void setType(Type type) {
        this.type = type;
    }

    public BigDecimal getCleanPanel() {
        return this.cleanPanel;
    }

    public void setCleanPanel(BigDecimal cleanPanel) {
        this.cleanPanel = cleanPanel;
    }

    public BigDecimal getAssy() {
        return this.assy;
    }

    public void setAssy(BigDecimal assy) {
        this.assy = assy;
    }

    public BigDecimal getPacking() {
        return this.packing;
    }

    public void setPacking(BigDecimal packing) {
        this.packing = packing;
    }

    public BigDecimal getBiCost() {
        return this.biCost;
    }

    public void setBiCost(BigDecimal biCost) {
        this.biCost = biCost;
    }

    public Integer getVibration() {
        return this.vibration;
    }

    public void setVibration(Integer vibration) {
        this.vibration = vibration;
    }

    public Integer getHiPotLeakage() {
        return this.hiPotLeakage;
    }

    public void setHiPotLeakage(Integer hiPotLeakage) {
        this.hiPotLeakage = hiPotLeakage;
    }

    public BigDecimal getColdBoot() {
        return this.coldBoot;
    }

    public void setColdBoot(BigDecimal coldBoot) {
        this.coldBoot = coldBoot;
    }

    public BigDecimal getWarmBoot() {
        return this.warmBoot;
    }

    public void setWarmBoot(BigDecimal warmBoot) {
        this.warmBoot = warmBoot;
    }

    public BigDecimal getAssyToT1() {
        return this.assyToT1;
    }

    public void setAssyToT1(BigDecimal assyToT1) {
        this.assyToT1 = assyToT1;
    }

    public BigDecimal getT2ToPacking() {
        return this.t2ToPacking;
    }

    public void setT2ToPacking(BigDecimal t2ToPacking) {
        this.t2ToPacking = t2ToPacking;
    }

    public String getBurnIn() {
        return this.burnIn;
    }

    public void setBurnIn(String burnIn) {
        this.burnIn = burnIn;
    }

    public BigDecimal getBiTime() {
        return this.biTime;
    }

    public void setBiTime(BigDecimal biTime) {
        this.biTime = biTime;
    }

    public BigDecimal getBiTemperature() {
        return this.biTemperature;
    }

    public void setBiTemperature(BigDecimal biTemperature) {
        this.biTemperature = biTemperature;
    }

    public Integer getSpeOwnerId() {
        return this.speOwnerId;
    }

    public void setSpeOwnerId(Integer speOwnerId) {
        this.speOwnerId = speOwnerId;
    }

    public Integer getEeOwnerId() {
        return this.eeOwnerId;
    }

    public void setEeOwnerId(Integer eeOwnerId) {
        this.eeOwnerId = eeOwnerId;
    }

    public Integer getQcOwnerId() {
        return this.qcOwnerId;
    }

    public void setQcOwnerId(Integer qcOwnerId) {
        this.qcOwnerId = qcOwnerId;
    }

    public String getAssyPackingSop() {
        return this.assyPackingSop;
    }

    public void setAssyPackingSop(String assyPackingSop) {
        this.assyPackingSop = assyPackingSop;
    }

    public Integer getKeypartA() {
        return this.keypartA;
    }

    public void setKeypartA(Integer keypartA) {
        this.keypartA = keypartA;
    }

    public Integer getKeypartB() {
        return this.keypartB;
    }

    public void setKeypartB(Integer keypartB) {
        this.keypartB = keypartB;
    }

    public String getPreAssy() {
        return this.preAssy;
    }

    public void setPreAssy(String preAssy) {
        this.preAssy = preAssy;
    }

    public String getBabFlow() {
        return this.babFlow;
    }

    public void setBabFlow(String babFlow) {
        this.babFlow = babFlow;
    }

    public String getTestFlow() {
        return this.testFlow;
    }

    public void setTestFlow(String testFlow) {
        this.testFlow = testFlow;
    }

    public String getPackingFlow() {
        return this.packingFlow;
    }

    public void setPackingFlow(String packingFlow) {
        this.packingFlow = packingFlow;
    }

    public String getPartLink() {
        return this.partLink;
    }

    public void setPartLink(String partLink) {
        this.partLink = partLink;
    }

    public String getNIn1CollectionBox() {
        return this.NIn1CollectionBox;
    }

    public void setNIn1CollectionBox(String NIn1CollectionBox) {
        this.NIn1CollectionBox = NIn1CollectionBox;
    }

    public String getPartNoAttrMaintain() {
        return this.partNoAttrMaintain;
    }

    public void setPartNoAttrMaintain(String partNoAttrMaintain) {
        this.partNoAttrMaintain = partNoAttrMaintain;
    }

    public Date getModifiedDate() {
        return this.modifiedDate;
    }

    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }

    public Set getLabelInfos() {
        return this.labelInfos;
    }

    public void setLabelInfos(Set labelInfos) {
        this.labelInfos = labelInfos;
    }

    public Set getPendings() {
        return this.pendings;
    }

    public void setPendings(Set pendings) {
        this.pendings = pendings;
    }

}
