package com.advantech.entity;
// Generated 2017/3/13 上午 09:50:39 by Hibernate Tools 4.3.1

import com.google.gson.annotations.Expose;
import java.math.BigDecimal;
import java.util.Date;

/**
 * SheetIe generated by hbm2java
 */
public class SheetIe implements java.io.Serializable {

    @Expose
    private int id;
    @Expose
    private Model model;
    @Expose
    private BigDecimal totalModule;
    @Expose
    private Integer assyStations;
    @Expose
    private Integer packingStations;
    @Expose
    private BigDecimal assyLeadTime;
    @Expose
    private BigDecimal assyKanbanTime;
    @Expose
    private BigDecimal packingLeadTime;
    @Expose
    private BigDecimal packingKanbanTime;
    @Expose
    private Date modifiedDate;

    public SheetIe() {
    }

    public SheetIe(int id) {
        this.id = id;
    }

    public SheetIe(int id, Model model, BigDecimal totalModule, Integer assyStations, Integer packingStations, BigDecimal assyLeadTime, BigDecimal assyKanbanTime, BigDecimal packingLeadTime, BigDecimal packingKanbanTime, Date modifiedDate) {
        this.id = id;
        this.model = model;
        this.totalModule = totalModule;
        this.assyStations = assyStations;
        this.packingStations = packingStations;
        this.assyLeadTime = assyLeadTime;
        this.assyKanbanTime = assyKanbanTime;
        this.packingLeadTime = packingLeadTime;
        this.packingKanbanTime = packingKanbanTime;
        this.modifiedDate = modifiedDate;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public Model getModel() {
        return this.model;
    }

    public void setModel(Model model) {
        this.model = model;
    }

    public BigDecimal getTotalModule() {
        return this.totalModule;
    }

    public void setTotalModule(BigDecimal totalModule) {
        this.totalModule = totalModule;
    }

    public Integer getAssyStations() {
        return this.assyStations;
    }

    public void setAssyStations(Integer assyStations) {
        this.assyStations = assyStations;
    }

    public Integer getPackingStations() {
        return this.packingStations;
    }

    public void setPackingStations(Integer packingStations) {
        this.packingStations = packingStations;
    }

    public BigDecimal getAssyLeadTime() {
        return this.assyLeadTime;
    }

    public void setAssyLeadTime(BigDecimal assyLeadTime) {
        this.assyLeadTime = assyLeadTime;
    }

    public BigDecimal getAssyKanbanTime() {
        return this.assyKanbanTime;
    }

    public void setAssyKanbanTime(BigDecimal assyKanbanTime) {
        this.assyKanbanTime = assyKanbanTime;
    }

    public BigDecimal getPackingLeadTime() {
        return this.packingLeadTime;
    }

    public void setPackingLeadTime(BigDecimal packingLeadTime) {
        this.packingLeadTime = packingLeadTime;
    }

    public BigDecimal getPackingKanbanTime() {
        return this.packingKanbanTime;
    }

    public void setPackingKanbanTime(BigDecimal packingKanbanTime) {
        this.packingKanbanTime = packingKanbanTime;
    }

    public Date getModifiedDate() {
        return this.modifiedDate;
    }

    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }

}
